package com.cognixia.jump.codingproblems;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;

public class Challenges9_21 {
	
	private boolean isPal = false;
	private String student = "not found";
	private int index = 0;
	/*
	 * 1. Write a program that stores a list of strings, and the Strings are Student names.  
	 * Make a list of at least 5 names.
	 * the class list is already generated by an admin (you make the list).
	 * have a user menu to input a index of a student, and check to see what the student name is, at that index.
	 * have exception handling in place, for the case that the index is out of bounds.
	 * Bonus: be able to look up a student (a String) in the list by name.
	 * Bonus: be able to take user input to add a student to the already existing list.
	 */
	public Challenges9_21() {
	}
	
	public void problem1(ArrayList<String> strArray) {
		Scanner input = new Scanner(System.in);
		System.out.print("Type I to lookup by index \nType N to lookup by name \nType A to add to existing list\n");
		switch(input.next()) {
			case "I":
				Scanner input2 = new Scanner(System.in);
				System.out.print("Input the student's position in the list (starting at 1): ");
				try {
					student = strArray.get(input.nextInt()-1);
					System.out.println("Selected student was " + student);
					
				} catch (InputMismatchException e) {
					System.out.println("Input a integer only.");
				
				} catch (ArrayIndexOutOfBoundsException e) {
					System.out.println("There are not that many students");
			
				} catch (Exception e) {
					e.printStackTrace();
				} 
			input2.close();
			break;
			case "N":
				Scanner input3 = new Scanner(System.in);
				System.out.println("Input the student's name: ");
				try {
					String inString = input3.next();
					for (int i = 0; i < (strArray.size()); i++) {
						if (strArray.get(i).equals(inString)) {
							index = i + 1;
						} 
					}
					if (index > 0) {
						System.out.println("Selected student is at position " + (index));
					}
					else {
						System.out.println("Student is not in the list");
					}
				} catch (Exception e) {
					e.printStackTrace();
				} 
			input3.close();	
			case "A":
				Scanner input4 = new Scanner(System.in);
				System.out.println("Input the new student's name: ");
				student = input4.next();
				if (!strArray.contains(student)) {
					strArray.add(student);
				} else {
					System.out.println("Student is already present");
				}
			input4.close();
		}	
		input.close();
	}

	/*
	 * 2. Write a program that has two numbers, x and y.  Be able to assign values to x and y, and then 
	 * swap their values so that x is now y, and y is now x.  Do this without using a third, temporary variable. 
	 * HINT - this is purely math.
	 */
	public int[] problem2(int[] nums) {
		nums[0] = nums[0] + nums[1];
		nums[1] = nums[0] - nums[1];
		nums[0] = nums[0] - nums[1];
		return nums;
	}
	
	/* 3. Palindrome - word if reversed still has the same spelling as it would be forward, ie. "wow".  
	 * Write a method that takes in a String, and returns true or false if that input String is a palindrome.  
	 * Make it so case sensitivity does NOT matter.
	 */
	public boolean problem3(String str) {
		String s = str;
		double mid = Math.floor(s.length() / 2);
		int indexLength = s.length() - 1;
		for (int i = 0; i < mid; i++) {
			if (Character.toLowerCase(s.charAt(i)) ==  Character.toLowerCase(s.charAt(indexLength-i))) {
				isPal = true;
			} else {
				break;
			}
		}
		return isPal;
	}
	
}
